# Generated by Django 3.2 on 2023-05-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0002_builders_additional_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='builders',
            name='additional_field2',
            field=models.CharField(default='default value', max_length=100),
        ),
    ]
