# Generated by Django 3.2 on 2023-05-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0003_builders_additional_field2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
            ],
        ),
    ]
